<a href="https://colab.research.google.com/github/nurshatfateh/WebScraping-NaturalLanguageProcessing/blob/main/FInal_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
url = 'https://raw.githubusercontent.com/nurshatfateh/WebScraping-NaturalLanguageProcessing/main/newsdata.csv'
collection = pd.read_csv(url,encoding = 'unicode_escape')
collection

,date,url
0,8/31/2020 22:41,https://www.dhakatribune.com/bangladesh/nation...
1,8/31/2020 22:41,http://m.thedailynewnation.com/news/261789/sal...
2,8/31/2020 22:41,https://bdnews24.com/bangladesh/2020/08/30/dha...
3,8/31/2020 22:46,https://www.thedailystar.net/opinion/news/pass...
4,8/31/2020 22:47,https://www.dhakatribune.com/bangladesh/nation...
...,...,...
6622,"Jan 25, 2023, 04:54:46",https://www.latestly.com/socially/india/news/s...
6623,"Jan 25, 2023, 19:54:15",https://www.dhakatribune.com/op-ed/2023/01/26/...
6624,"Jan 25, 2023, 19:54:15",https://bdnews24.com/bangladesh/pvxt6pnv8s
6625,"Jan 25, 2023, 21:01:41",https://bdnews24.com/world/south-east-asia/2wu...
6626,"Jan 25, 2023, 21:06:31",https://www.jagonews24.com/en/national/news/66465

In [ ]:
collection['url'][0]

'https://www.dhakatribune.com/bangladesh/nation/2020/08/30/teenage-cleaner-killed-in-dhaka-road-crash'

In [ ]:
url = 'https://raw.githubusercontent.com/nurshatfateh/WebScraping-NaturalLanguageProcessing/main/dictionary.csv'
df = pd.read_csv(url)
df.head()

,1,1.1,comilla,কুমিল্লা,23.4682747,91.1788135,www.comilla.gov.bd
0,2,1,feni,ফেনী,23.023231,91.384084,www.feni.gov.bd
1,3,1,brahmanbaria,ব্রাহ্মণবাড়িয়া,23.9570904,91.111929,www.brahmanbaria.gov.bd
2,4,1,rangamati,রাঙ্গামাটি,22.65561018,92.175411,www.rangamati.gov.bd
3,5,1,noakhali,নোয়াখালী,22.869563,91.099398,www.noakhali.gov.bd
4,6,1,chandpur,চাঁদপুর,23.2332585,90.671291,www.chandpur.gov.bd

In [ ]:
pip install newspaper3k

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: newspaper3k in /usr/local/lib/python3.8/dist-packages (0.2.8)
Requirement already satisfied: jieba3k>=0.35.1 in /usr/local/lib/python3.8/dist-packages (from newspaper3k) (0.35.1)
Requirement already satisfied: requests>=2.10.0 in /usr/local/lib/python3.8/dist-packages (from newspaper3k) (2.25.1)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.8/dist-packages (from newspaper3k) (2.8.2)
Requirement already satisfied: feedparser>=5.2.1 in /usr/local/lib/python3.8/dist-packages (from newspaper3k) (6.0.10)
Requirement already satisfied: feedfinder2>=0.0.4 in /usr/local/lib/python3.8/dist-packages (from newspaper3k) (0.0.4)
Requirement already satisfied: PyYAML>=3.11 in /usr/local/lib/python3.8/dist-packages (from newspaper3k) (6.0)
Requirement already satisfied: lxml>=3.6.0 in /usr/local/lib/python3.8/dist-packages (from newspaper3k) (4.9.2)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /usr/local/lib/python3.8/dist-packages (from newspaper3k) (4.6.3)
Requirement already satisfied: tldextract>=2.0.1 in /usr/local/lib/python3.8/dist-packages (from newspaper3k) (3.4.0)
Requirement already satisfied: nltk>=3.2.1 in /usr/local/lib/python3.8/dist-packages (from newspaper3k) (3.7)
Requirement already satisfied: Pillow>=3.3.0 in /usr/local/lib/python3.8/dist-packages (from newspaper3k) (8.4.0)
Requirement already satisfied: cssselect>=0.9.2 in /usr/local/lib/python3.8/dist-packages (from newspaper3k) (1.2.0)
Requirement already satisfied: tinysegmenter==0.3 in /usr/local/lib/python3.8/dist-packages (from newspaper3k) (0.3)
Requirement already satisfied: six in /usr/local/lib/python3.8/dist-packages (from feedfinder2>=0.0.4->newspaper3k) (1.15.0)
Requirement already satisfied: sgmllib3k in /usr/local/lib/python3.8/dist-packages (from feedparser>=5.2.1->newspaper3k) (1.0.0)
Requirement already satisfied: click in /usr/local/lib/python3.8/dist-packages (from nltk>=3.2.1->newspaper3k) (7.1.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.8/dist-packages (from nltk>=3.2.1->newspaper3k) (2022.6.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.8/dist-packages (from nltk>=3.2.1->newspaper3k) (1.2.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from nltk>=3.2.1->newspaper3k) (4.64.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests>=2.10.0->newspaper3k) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests>=2.10.0->newspaper3k) (1.24.3)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.10.0->newspaper3k) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests>=2.10.0->newspaper3k) (2.10)
Requirement already satisfied: filelock>=3.0.8 in /usr/local/lib/python3.8/dist-packages (from tldextract>=2.0.1->newspaper3k) (3.9.0)
Requirement already satisfied: requests-file>=1.4 in /usr/local/lib/python3.8/dist-packages (from tldextract>=2.0.1->newspaper3k) (1.5.1)

In [ ]:
from newspaper import Article
import spacy
from spacy.matcher import Matcher

In [ ]:
def extract_article_from_url(url):
  a = Article(url)
  a.download()
  a.parse()
  return a.text, a.publish_date

In [ ]:
def sentence_giver(doc, start, end):
  s = start
  while str(doc[s]) != '.':
    s = s - 1
    if s < 0:
      break
  e = end
  while str(doc[e]) != '.':

    e = e + 1

    if e > len(doc) - 1:
      break

  return str(doc[s+1:e])

In [ ]:
def location_finder(doc):
  locations = []
  sentences = []
  matcher = Matcher(nlp.vocab)
  pattern = [{"ENT_TYPE": "GPE"}]
  matcher.add("Location", [pattern])
  matches = matcher(doc)
  for match_id, start, end in matches:
    sentence = sentence_giver(doc, start, end)
    value = l_detail_filter(sentence)
    if value == 1:
      sentences.append(sentence)
      locations.append(doc[start:end])
  return locations, sentences

def l_detail_filter(data):
  data = nlp(data)
  matcher = Matcher(nlp.vocab)
  pattern1 = [{"LEMMA": "accident", "POS": "VERB"}]
  pattern2 = [{"LEMMA": "die", "POS": "VERB"}]
  pattern3 = [{"LEMMA": "collide", "POS": "VERB"}]
  pattern4 = [{"LEMMA": "crash", "POS": "VERB"}]
  pattern5 = [{"LEMMA": "kill", "POS": "VERB"}]
  pattern0 = [{"LOWER": "in"}]

  matcher.add("N_Filter", [pattern1])
  matches = matcher(data)
  if len(matches) != 0:
    return 1
  else:
    matcher.add("N_Filter", [pattern2])
    matches = matcher(data)
    if len(matches) != 0:
      return 1
    else:
      matcher.add("N_Filter", [pattern3])
      matches = matcher(data)
      if len(matches) != 0:
        return 1
      else:
        matcher.add("N_Filter", [pattern4])
        matches = matcher(data)
        if len(matches) != 0:
          return 1
        else:
          matcher.add("N_Filter", [pattern5])
          matches = matcher(data)
          if len(matches) != 0:
            return 1
          else:
            matcher.add("N_Filter", [pattern0])
            matches = matcher(data)
            if len(matches) != 0:
              return 1
            else:
              return 0

In [ ]:
def number_finder(doc):
  numbers = []
  sentences = []
  matcher = Matcher(nlp.vocab)
  pattern = [{"LIKE_NUM": True}]
  matcher.add("Number", [pattern])
  matches = matcher(doc)
  for match_id, start, end in matches:
    sentence = sentence_giver(doc, start, end)
    value = n_detail_filter(sentence)
    if value == 1:
      sentences.append(sentence)
      numbers.append(str(doc[start:end]))
  return numbers, sentences

In [ ]:
def n_detail_filter(data):
  data = nlp(data)
  matcher = Matcher(nlp.vocab)
  pattern1 = [{"LEMMA": "kill", "POS": "VERB"}]
  pattern2 = [{"LEMMA": "die", "POS": "VERB"}]


  matcher.add("N_Filter", [pattern1])
  matches = matcher(data)
  if len(matches) != 0:
    return 1
  else:
    matcher.add("N_Filter", [pattern2])
    matches = matcher(data)
    if len(matches) != 0:
      return 1
    else:
      return 0

In [ ]:
loc=[]
dea=[]
veh1=[]
veh2=[]
veh3=[]
dat=[]
for zz in range(0,6625):

  print(zz)
  link=collection['url'][zz]





  try:
    article=Article(link)
    article.download()
    article.parse()
  except:
    continue
 
  import spacy 
  nlp = spacy.load('en_core_web_sm')
  sentence = article.text
  sentence = sentence.replace("-", ".")
  doc = nlp(sentence)




  for ent in doc.ents:
     for index, row in df.iterrows():
          if ent.text.lower()==row[2]:
           ent.label_='GPE'
           break     
  #print("---------------------------------------------------START-----------------------------------------------")
  #print(article.text)


  try:
    l_places, l_s = location_finder(doc)
  #print("ACCIDENT LOCATION: ",l_places)
  #print(l_s)
  except:
    continue

  try:  
    n_people, n_s = number_finder(doc)
    death=0
  except:
    continue

  if len(n_s)!=0:
    death=n_people[0]
    #print("Victim NUMBER: ",death)
  else:
    death="One"
    #print("Victim NUMBER: ",death)
  #print(n_s)
  z=[None,None,None]
  x=0
  #print("RELATED VEHICLES: ")
  vehicle = ['truck','bus','car','bike','motorcycle','rickshaw','tempo']
  for i in vehicle:
    for j in doc.text.split():
      if i in j:
        if j!='carrying':
          #print(i)
          z.insert(x, i)
          x=x+1
          break
  #print("News Date: ",collection['date'][zz])
  date=collection['date'][zz]
 
  
  if len(l_places) != 0:
    loc.append(l_places[0])
    dea.append(death)
    veh1.append(z[0])
    veh2.append(z[1])
    veh3.append(z[2])
    dat.append(date)  
    if len(l_places)>1:
      loc.append(l_places[1])
      dea.append(death)
      veh1.append(z[0])
      veh2.append(z[1])
      veh3.append(z[2])
      dat.append(date)
  
 

 
  #print("-------------------------------------------------END-------------------------------------------------")

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675

In [ ]:
d = {'ACCIDENT LOCATION':loc,'ACCIDENT Date':dat,'Victim NUMBER':dea,'Vehicle 1':veh1,'Vehicle 2':veh2,'Vehicle 3':veh3}
df = pd.DataFrame(d)
df = df.dropna(axis=0, subset=['Vehicle 1'])

df

,ACCIDENT LOCATION,ACCIDENT Date,Victim NUMBER,Vehicle 1,Vehicle 2,Vehicle 3
2,(Habiganj),9/4/2020 22:02,One,rickshaw,None,None
3,(Habiganj),9/4/2020 22:02,One,rickshaw,None,None
4,(Nishikanda),9/4/2020 22:02,Three,bus,rickshaw,None
5,(Boalkhali),9/4/2020 22:02,One,bus,car,tempo
6,(Munshiganj),9/4/2020 22:02,One,bus,car,tempo
7,(Paraichak),9/4/2020 22:02,Two,bus,None,None
8,(Dhamrai),9/5/2020 22:42,3,bus,None,None
9,(Bangladesh),9/5/2020 22:42,3,bus,None,None
10,(Kaliganj),9/5/2020 22:42,One,truck,bus,car
13,(Nababganj),9/5/2020 22:46,Three,bus,rickshaw,None
14,(Keraniganj),9/5/2020 22:46,Three,bus,rickshaw,None
15,(Dhamrai),9/5/2020 22:59,3,bus,None,None
16,(Bangladesh),9/5/2020 22:59,3,bus,None,None